export const OPEN_APP_OVERLAY = 'OPEN_APP_OVERLAY';
export const CLOSE_APP_OVERLAY = 'CLOSE_APP_OVERLAY';

export const START_LOADING = 'START_LOADING';
export const SET_LOADING_REQUEST_PROGRESS = 'SET_LOADING_REQUEST_PROGRESS';
export const END_LOADING = 'END_LOADING';

export const FETCH_BIBLE_VERSIONS_START = 'FETCH_BIBLE_VERSIONS_START';
export const FETCH_BIBLE_VERSIONS_SUCCESS = 'FETCH_BIBLE_VERSIONS_SUCCESS';
export const FETCH_BIBLE_VERSIONS_FAIL = 'FETCH_BIBLE_VERSIONS_FAIL';

export const FETCH_BIBLE_VERSION_START = 'FETCH_BIBLE_VERSION_START';
export const FETCH_BIBLE_VERSION_SUCCESS = 'FETCH_BIBLE_VERSION_SUCCESS';
export const FETCH_BIBLE_VERSION_FAIL = 'FETCH_BIBLE_VERSION_FAIL';

export const FETCH_BIBLE_BOOKS_START = 'FETCH_BIBLE_BOOKS_START';
export const FETCH_BIBLE_BOOKS_SUCCESS = 'FETCH_BIBLE_BOOKS_SUCCESS';
export const FETCH_BIBLE_BOOKS_FAIL = 'FETCH_BIBLE_BOOKS_FAIL';

export const FETCH_BIBLE_MILESTONES_START = 'FETCH_BIBLE_MILESTONES_START';
export const FETCH_BIBLE_MILESTONES_SUCCESS = 'FETCH_BIBLE_MILESTONES_SUCCESS';
export const FETCH_BIBLE_MILESTONES_FAIL = 'FETCH_BIBLE_MILESTONES_FAIL';

export const FETCH_BIBLE_BOOK_START = 'FETCH_BIBLE_BOOK_START';
export const FETCH_BIBLE_BOOK_SUCCESS = 'FETCH_BIBLE_BOOK_SUCCESS';
export const FETCH_BIBLE_BOOK_FAIL = 'FETCH_BIBLE_BOOK_FAIL';

export const SET_BIBLE_CHAPTER = 'SET_BIBLE_CHAPTER';

export const FETCH_BIBLE_VERSES_START = 'FETCH_BIBLE_VERSES_START';
export const FETCH_BIBLE_VERSES_SUCCESS = 'FETCH_BIBLE_VERSES_SUCCESS';
export const FETCH_BIBLE_VERSES_FAIL = 'FETCH_BIBLE_VERSES_FAIL';
export const SET_LOADING_BIBLE_VERSES_PROGRESS = 'SET_LOADING_BIBLE_VERSES_PROGRESS';

export const OPEN_BIBLE_SIDEBAR_ITEM = 'OPEN_BIBLE_SIDEBAR_ITEM';
export const CLOSE_BIBLE_SIDEBAR = 'CLOSE_BIBLE_SIDEBAR';